more verbose, startded, multiple wine prefixes, stuff

diff --git a/ahk/ahk b/ahk/ahk
--- a/ahk/ahk
+++ b/ahk/ahk
@@ -2,6 +2,13 @@
 
 d=$(dirname "$0")
 b=${1##*/}
+
+if [ ! -f "$d/AutoHotkey.exe" ]; then
+	echo "AutoHotkey not found."
+	echo "Download it with ./download"
+	exit 1
+fi
+
 echo "Running AutoHotkey script ${b%.*}..."
 
 wine "$d/AutoHotkey.exe" "$1"
diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,12 +2,18 @@
 
 . ./env
 
+if [ ! -f "dl/installer.exe" ]; then
+	echo "JJ2 installer not found."
+	echo "Load it with ./download <url> or ./download file://<path>"
+	exit 1
+fi
+
 #echo "Initializing wine prefix..."
 #xvfb-run -a --server-args="-screen 0 640x480x8" wineboot
 
 # Install JJ2
-echo "Running Jazz Jackrabbit 2 installer..."
+echo "Starting Jazz Jackrabbit 2 installer..."
 xvfb-run -a --server-args="-screen 0 640x480x8" ahk/ahk ahk/install.ahk
 
 # install JJ2 Plus
-. ./plusify
+. ./install-plus
diff --git a/start b/start
--- a/start
+++ b/start
@@ -10,8 +10,14 @@ if [ -z "$path" ]; then
 fi
 
 exe="$path/Jazz2+.exe"
-flags="-windowed -menu -nolog -noddrawwin -noddraw -noddrawmemcheck -nojoy -noerrtrap -nocpucheck $extraflags"
+flags="-windowed -menu -nolog -nospy -noddrawwin -noddraw -noddrawmemcheck -nojoy -noerrtrap -nocpucheck $extraflags"
 
-echo "Starting $exe $flags"
+if [ ! -f "$exe" ]; then
+	echo "$exe not found"
+	exit 1
+fi
+
+echo "Launching $exe $flags"
+echo "Running in wine prefix $WINEPREFIX"
 
 wine start /wait "$exe" $flags
